{% set version = "1.5-0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-elliptic
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/elliptic_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/elliptic/elliptic_{{ version }}.tar.gz
  sha256: c52583a115ec298dee59e201e734513b94e54bee3798e74ca1a7a38f89599495

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
  run:
    - r-base
    - r-mass

test:
  commands:
    - $R -e "library('elliptic')"           # [not win]
    - "\"%R%\" -e \"library('elliptic')\""  # [win]

about:
  home: https://github.com/RobinHankin/elliptic.git
  license: GPL-2
  summary: ' A suite of elliptic and related functions including Weierstrass and Jacobi forms.  Also includes various tools for manipulating and visualizing complex functions.'
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: elliptic
# Version: 1.4-0
# Title: Weierstrass and Jacobi Elliptic Functions
# Authors@R: person(given=c("Robin", "K. S."), family="Hankin", role = c("aut","cre"), email="hankin.robin@gmail.com", comment = c(ORCID = "0000-0001-5982-0415"))
# Depends: R (>= 2.5.0)
# Imports: MASS
# Suggests: emulator, calibrator (>= 1.2-8)
# SystemRequirements: pari/gp
# Description:  A suite of elliptic and related functions including Weierstrass and Jacobi forms.  Also includes various tools for manipulating and visualizing complex functions.
# Maintainer: Robin K. S. Hankin <hankin.robin@gmail.com>
# License: GPL-2
# URL: https://github.com/RobinHankin/elliptic.git
# BugReports: https://github.com/RobinHankin/elliptic/issues
# NeedsCompilation: no
# Packaged: 2019-03-14 00:30:29 UTC; rhankin
# Author: Robin K. S. Hankin [aut, cre] (<https://orcid.org/0000-0001-5982-0415>)
# Repository: CRAN
# Date/Publication: 2019-03-14 06:10:02 UTC
