appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: npjfcfeVsybpi6qw7U1rXdHk0jlAaSP9ILVkARDJYAGdC5P9UZd2lf2gDQEUJatZeheB4PqIbGcKUi42YtTPvBBjtjViedpFvLeZ4ibcC+Qkrm85N/OTzh2SG7Nxrkb1E62KziK2UUvy8rwzGPIv5KfDjaMfrc4mzfabDFjYkvbwLkJ2GDUYy72w7hrvtqU+b6Dd2PHleOqAJALJfJcGdAezvi+Iohv8yiePEEYEabIPrykv6GESNinB8WCuyBxkdXQWsrD5LhrnR6xc8O+U+4YGQv0Yn0Nsuf/gaeCm5zTmP6wWNYcbLIvJNPU3vNkPJ5rOq5rfkz3zB890cPZ3dm05t+KyEk2/uwFixCHMeiiVPUivGUP7sExwvoQdSR6sElQikeaGzrCHbdYIvaEyoblntNhxoJHCEmUfbUKk5HvxOo2ZMQeOEUkPISk4yUS/jqMQR6F1ZWOvAceTCb5Qo+fZPaWUOwNciUxINa6jG1yfZE0i9yNVjI3uJb7udx+ur0DR3G0arzkjECpdde0En+QvHTa8+llYme6JmnVQmn4DaCsS14Aht0BTSX/YcqzKVmfhmBsDQ4+wO787baIsN9RCKJMPYSJCRJ/ulDGEMu84QHMoy+M13XElcxy1rsaA/L0i5DFUzx9CEzZjoKbnXWUKhoWHoiA6rnAWwhehuH4=
conda_forge_output_validation: true
